[project]
name = "bilibili-srt-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.4.2",
    "openai-whisper>=20240930",
    "selenium>=4.32.0",
]
